# Generated by Django 3.0.5 on 2020-04-09 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_code', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'report_card_class',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_code', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ClassSection.Classes')),
            ],
            options={
                'db_table': 'report_card_section',
            },
        ),
    ]
