# Generated by Django 3.0.5 on 2020-04-24 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_email_address', models.CharField(max_length=100)),
                ('parent_image', models.ImageField(null=True, upload_to='Images/student/', verbose_name='Image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_card_parent',
            },
        ),
    ]
