# Generated by Django 3.0.5 on 2020-04-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_email_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_name',
            field=models.CharField(max_length=100),
        ),
    ]
