# Generated by Django 3.0.5 on 2020-04-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0002_auto_20200424_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
    ]
