# Generated by Django 3.0.5 on 2020-04-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0004_auto_20200424_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_image',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
