# Generated by Django 3.0.5 on 2020-04-06 19:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('fname', models.CharField(default='schoolink', max_length=100)),
                ('user_type', models.PositiveSmallIntegerField(default=1)),
                ('login_time', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=255)),
                ('is_delete', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
