# Generated by Django 3.0.5 on 2020-04-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='login_time',
        ),
    ]
